using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace joblogs
{
    // Summary Stats takes as input, the memEff file generated by MemEff.GenerateMemEffFile()
    // changes here correlate with MemEff.cs in soluiton Longleaf for Auzre function
    class SummaryStatsModel
    {
        public string Id { get; set; }              // either User or Account
        public string Account { get; set; }         // for userStats, helpful to carry forward the account to which user is associated. this field has no meaning for accountStats
        public long JobCount { get; set; } = 0;
        public long CoreHoursTotal { get; set; } = 0;
        public long GBHoursReqTotal { get; set; } = 0;
        public long GBHoursUsedTotal { get; set; } = 0;
        public string JobIDFirst { get; set; }
        public string JobIDLast { get; set; }
    }
    class SummaryStats
    {
        private static Dictionary<string, SummaryStatsModel> UserStats = new Dictionary<string, SummaryStatsModel>();
        private static Dictionary<string, SummaryStatsModel> AccountStats = new Dictionary<string, SummaryStatsModel>();
        public static void GenerateFile(Configurator cfg)
        {
            int counter = 0;
            string line = "";

            var colRef = Util.GetAllColumnReferences(cfg, cfg.MemEffFile);

            using (StreamReader sr = new StreamReader(cfg.MemEffFile))
            {
                line = sr.ReadLine();   // skip header row

                while ((line = sr.ReadLine()) != null)
                {
                    var thisRec = line.Split(cfg.Delimiter);

                    // need to flatten multistep JobID's: if JobID contains "_n", simply remove it
                    int locationOfUnderscore = thisRec[colRef["JobID"]].IndexOf("_");
                    if (locationOfUnderscore != -1)
                        thisRec[colRef["JobID"]] = thisRec[colRef["JobID"]].Substring(0, locationOfUnderscore);

                    if (!UserStats.ContainsKey(thisRec[colRef["User"]]))
                    {
                        var temp = new SummaryStatsModel
                        {
                            Id = thisRec[colRef["User"]],
                            Account = thisRec[colRef["Account"]],
                            JobIDFirst = thisRec[colRef["JobID"]],
                            JobIDLast = thisRec[colRef["JobID"]]
                        };

                        UserStats.Add(thisRec[colRef["User"]], temp);
                    }

                    if (!AccountStats.ContainsKey(thisRec[colRef["Account"]]))
                    {
                        var temp = new SummaryStatsModel
                        {
                            Id = thisRec[colRef["Account"]],
                            JobIDFirst = thisRec[colRef["JobID"]],
                            JobIDLast = thisRec[colRef["JobID"]]
                        };
                        AccountStats.Add(thisRec[colRef["Account"]], temp);
                    }


                    int GBHoursReq = int.Parse(thisRec[colRef["GBHoursRequested"]]);
                    int GBHoursUsed = int.Parse(thisRec[colRef["GBHoursUsed"]]);

                    double hrs = Util.ConvertTimeStringToHours(thisRec[colRef["Elapsed"]]);
                    int CoreHours = (int)(hrs * int.Parse(thisRec[colRef["NCPUS"]]));


                    long thisRecJobID = long.Parse(thisRec[colRef["JobID"]]);

                    // used for debugging:
                        //if (!long.TryParse(UserStats[thisRec[colRef["User"]]].JobIDFirst, out jobIDFirst))
                        //    Console.WriteLine($"failed long.TryParse: {thisRec[colRef["JobID"]]}");
                        //if (!long.TryParse(UserStats[thisRec[colRef["User"]]].JobIDLast, out jobIDLast))
                        //    Console.WriteLine($"failed long.TryParse: {UserStats[thisRec[colRef["User"]]].JobIDLast}");

                    if (thisRecJobID < long.Parse(UserStats[thisRec[colRef["User"]]].JobIDFirst))
                        UserStats[thisRec[colRef["User"]]].JobIDFirst = thisRecJobID.ToString();

                    if (thisRecJobID > long.Parse(UserStats[thisRec[colRef["User"]]].JobIDLast))
                        UserStats[thisRec[colRef["User"]]].JobIDLast = thisRecJobID.ToString();

                    UserStats[thisRec[colRef["User"]]].JobCount += 1;
                    UserStats[thisRec[colRef["User"]]].GBHoursReqTotal += GBHoursReq;
                    UserStats[thisRec[colRef["User"]]].GBHoursUsedTotal += GBHoursUsed;
                    UserStats[thisRec[colRef["User"]]].CoreHoursTotal += CoreHours;


                    AccountStats[thisRec[colRef["Account"]]].JobCount += 1;
                    AccountStats[thisRec[colRef["Account"]]].GBHoursReqTotal += GBHoursReq;
                    AccountStats[thisRec[colRef["Account"]]].GBHoursUsedTotal += GBHoursUsed;
                    AccountStats[thisRec[colRef["Account"]]].CoreHoursTotal += CoreHours;

                    if (thisRecJobID < long.Parse(AccountStats[thisRec[colRef["Account"]]].JobIDFirst))
                        AccountStats[thisRec[colRef["Account"]]].JobIDFirst = thisRecJobID.ToString();

                    if (thisRecJobID > long.Parse(AccountStats[thisRec[colRef["Account"]]].JobIDLast))
                        AccountStats[thisRec[colRef["Account"]]].JobIDLast = thisRecJobID.ToString();

                    counter++;
                    if (counter % 1000 == 0)
                        Console.Write($"\r  Rows Processed: {String.Format("{0:n0}", counter)}");
                }

                Console.Write($"\r  Rows Processed: {String.Format("{0:n0}", counter)}{Environment.NewLine}");
            }

            WriteOutput(cfg, "User", UserStats);
            WriteOutput(cfg, "Account", AccountStats);
        }

        private static void WriteOutput(Configurator cfg, string UserOrAccount, Dictionary<string, SummaryStatsModel> d)
        {
            StringBuilder sb = new StringBuilder();

            sb.Append(UserOrAccount);
            sb.Append(cfg.Delimiter);

            // hack to bring forward the account to which user is associated
            if (UserOrAccount == "User")
            {
                sb.Append("Account");
                sb.Append(cfg.Delimiter);
            }

            sb.Append("JobCount");
            sb.Append(cfg.Delimiter);
            sb.Append("AvgCoreHoursPerJob");
            sb.Append(cfg.Delimiter);
            sb.Append("CoreHours");
            sb.Append(cfg.Delimiter);
            sb.Append("GBHoursAllocated");
            sb.Append(cfg.Delimiter);
            sb.Append("GBHoursUsed");
            sb.Append(cfg.Delimiter);
            sb.Append("PercentGBHoursUsed");
            sb.Append(cfg.Delimiter);
            sb.Append("JobIDFirst");
            sb.Append(cfg.Delimiter);
            sb.Append("JobIDLast");
            sb.Append(Environment.NewLine);

            foreach (var item in d)
            {
                sb.Append(item.Key);
                sb.Append(cfg.Delimiter);

                // hack to bring forward the account to which user is associated
                if (UserOrAccount == "User")
                {
                    sb.Append(item.Value.Account);
                    sb.Append(cfg.Delimiter);
                }

                sb.Append(item.Value.JobCount);
                sb.Append(cfg.Delimiter);

                double AvgCoreHrsPerJob = item.Value.CoreHoursTotal / item.Value.JobCount;
                sb.Append(Math.Round(AvgCoreHrsPerJob, 1));
                sb.Append(cfg.Delimiter);

                sb.Append(item.Value.CoreHoursTotal);
                sb.Append(cfg.Delimiter);

                sb.Append(item.Value.GBHoursReqTotal);
                sb.Append(cfg.Delimiter);

                sb.Append(item.Value.GBHoursUsedTotal);
                sb.Append(cfg.Delimiter);

                double pct = 0.0;
                if (item.Value.GBHoursReqTotal > 0)
                    pct = (item.Value.GBHoursUsedTotal / (double)item.Value.GBHoursReqTotal) * 100.0;
                sb.Append(Math.Round(pct, 1));
                sb.Append(cfg.Delimiter);

                sb.Append(item.Value.JobIDFirst);
                sb.Append(cfg.Delimiter);

                sb.Append(item.Value.JobIDLast);

                sb.Append(Environment.NewLine);
            }

            string outFile = Path.Combine(cfg.OutputLocation, $"summaryStats-{UserOrAccount}.txt");
            File.WriteAllText(outFile, sb.ToString());
            Console.WriteLine($"File written: {outFile}");
            sb.Clear();
        }


    }
}
